# Generated by Django 4.0.5 on 2022-10-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAMERA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.TextField()),
                ('LINK', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HUMIDITY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEGREE', models.IntegerField()),
                ('TIME', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='REMNANT_W',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WATER', models.IntegerField()),
                ('TIME', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TEMPERATURE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEMP', models.IntegerField()),
                ('TIME', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
