# Generated by Django 4.0.5 on 2022-10-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='TIME',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='remnant_w',
            name='TIME',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='TIME',
            field=models.DateTimeField(),
        ),
    ]
