# Generated by Django 4.0.5 on 2022-11-02 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.TextField()),
                ('PASSWORD', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SERVER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LINK', models.URLField()),
                ('TITLE', models.TextField()),
                ('CENTENT', models.TextField()),
                ('STATUS', models.IntegerField(default=0)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MFID.user')),
            ],
        ),
    ]
